CREATE TABLE Usuario (
	idUsuario BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nombreUsuario VARCHAR(50) NOT NULL,
	contrasenaUsuario VARCHAR(50) NOT NULL,
	emailUsuario VARCHAR(50) NOT NULL,
	idEmpleado BIGINT(20) NOT NULL,
    FOREIGN KEY (idEmpleado) REFERENCES Empleado (idEmpleado) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
