CREATE TABLE EmpArea (
	idEmpleado BIGINT(20) NOT NULL,
	idArea BIGINT(20) NOT NULL,
    FOREIGN KEY (idEmpleado) REFERENCES Empleado (idEmpleado) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (idArea) REFERENCES Area (idArea) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;