CREATE TABLE EmpEducacion (
	idEducacion BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	idEmpleado BIGINT(20) NOT NULL,
    FOREIGN KEY (idEducacion) REFERENCES Educacion (idEducacion) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (idEmpleado) REFERENCES Empleado (idEmpleado) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;