CREATE TABLE UsuarioRoles (
	idRolSistema BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	idUsuario BIGINT(20) NOT NULL,
    FOREIGN KEY (idRolSistema) REFERENCES RolSistema (idRolSistema) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (idUsuario) REFERENCES Usuario (idUsuario) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;