CREATE TABLE TerminalVenta (
	idTerminal BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nombreTerminal VARCHAR(50) NOT NULL,
	idUsuario BIGINT(20) NOT NULL,
    idSede BIGINT(20) NOT NULL,
    FOREIGN KEY (idSede) REFERENCES Sede (idSede) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (idUsuario) REFERENCES Usuario (idUsuario) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;