CREATE TABLE Direccion (
	idDireccion BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	direccion VARCHAR(50) NOT NULL,
	idDistrito BIGINT(20) NOT NULL,
	idEmpleado BIGINT(20) NOT NULL,
    FOREIGN KEY (idDistrito) REFERENCES Distrito (idDistrito) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (idEmpleado) REFERENCES Empleado (idEmpleado) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;