CREATE TABLE Cliente (
	idCliente BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    direccion VARCHAR(50) NOT NULL,
    telefono VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    tipoCliente INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;