CREATE TABLE ClienteNatural (
	idClienteNatural BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nombres VARCHAR(50) NOT NULL,
    apellidos VARCHAR(50) NOT NULL,
    DNI VARCHAR(50) NOT NULL,
    idCliente BIGINT(20) NOT NULL,
    FOREIGN KEY (idCliente) REFERENCES Cliente (idCliente) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;