CREATE TABLE Venta (
	idVenta BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nroFactura VARCHAR(50) NOT NULL,
    fecha VARCHAR(50) NOT NULL,    
    idTerminal BIGINT(20) NOT NULL,
    idCliente BIGINT(20) NOT NULL,
    FOREIGN KEY (idCliente) REFERENCES Cliente (idCliente) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (idTerminal) REFERENCES TerminalVenta (idTerminal) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;