CREATE TABLE DetalleVenta (
	idVenta BIGINT(20) NOT NULL,
	idServicio BIGINT(20) NOT NULL,
    cantidad BIGINT(20) NOT NULL,
    FOREIGN KEY (idServicio) REFERENCES Servicio (idServicio) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (idVenta) REFERENCES Venta (idVenta) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;